title:            Eyes On Code#Real Artists Ship
description:      A journal of this developer's life
logo:             logo.png
disqus_shortname: donhetguru
search:           true
# Change url to your domain. Leave localhost server or blank when working locally.
baseurl:          http://don.het.guru
#http://localhost:4000

# Owner/author information
owner:
  name:           Hetal Patel
  avatar:         profile-bg-white.png
  email:          
  # Social networking links used in footer. Update and remove as you like.
  twitter:        Hetal_Patel
  facebook:       
  github:         hetalsureshpatel
  stackexchange:  
  linkedin:       donhet
  instagram:      
  flickr:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    https://plus.google.com/110891118909852521870?rel=author

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in top navigation
# For external links add external: true
#- title: Google
#    url: http://www.google.co.uk
#   external: true
links:
  - title: About
    url: /about/
  - title: Posts
    url: /posts/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/London
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
#/:categories/:title/
permalink:   /:categories/:year/:month/:day/:title
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
